export type FruitExchange = {
  name: string;
  amount: string;
  emoji: string;
};

export const fruitExchanges: FruitExchange[] = [
  { name: "Ahududu", amount: "½ su bardağı", emoji: "🫐" },
  { name: "Ananas", amount: "1 ince dilim", emoji: "🍍" },
  { name: "Armut", amount: "1 orta boy", emoji: "🍐" },
  { name: "Ayva", amount: "½ orta boy", emoji: "🍏" },
  { name: "Böğürtlen", amount: "½ su bardağı", emoji: "🫐" },
  { name: "Çilek", amount: "12 adet", emoji: "🍓" },
  { name: "Dut", amount: "8 adet", emoji: "🫐" },
  { name: "Elma", amount: "1 küçük boy", emoji: "🍎" },
  { name: "Greyfurt", amount: "½ adet", emoji: "🍊" },
  { name: "Karpuz", amount: "5 üçgen dilim", emoji: "🍉" },
  { name: "Kavun", amount: "5 üçgen dilim", emoji: "🍈" },
  { name: "Kayısı", amount: "3 adet", emoji: "🍑" },
  { name: "Çağla", amount: "10 adet", emoji: "🌿" },
  { name: "Hünnap", amount: "5 adet", emoji: "🟤" },
  { name: "Kuru hurma", amount: "3 orta boy", emoji: "🌴" },
  { name: "Kuru incir", amount: "1 adet", emoji: "🟤" },
  { name: "Kuru kayısı", amount: "3 küçük boy", emoji: "🍑" },
  { name: "Kuru üzüm", amount: "1 yemek kaşığı", emoji: "🍇" },
  { name: "Mandalina", amount: "1 büyük boy", emoji: "🍊" },
  { name: "Muz", amount: "1 küçük boy", emoji: "🍌" },
  { name: "Nar", amount: "½ adet", emoji: "🔴" },
  { name: "Portakal", amount: "1 orta boy", emoji: "🍊" },
  { name: "Şeftali", amount: "1 orta boy", emoji: "🍑" },
  { name: "Taze incir", amount: "2 adet", emoji: "🟤" },
  { name: "Trabzon hurması", amount: "1 küçük boy", emoji: "🍅" },
  { name: "Turunç", amount: "1 orta boy", emoji: "🍊" },
  { name: "İğde", amount: "15-20 adet", emoji: "🟡" },
  { name: "Alıç", amount: "10-15 adet", emoji: "🍎" },
  { name: "Kırmızı erik", amount: "5 adet", emoji: "🟣" },
  { name: "Kiraz", amount: "12 adet", emoji: "🍒" },
  { name: "Kivi", amount: "1 orta boy", emoji: "🥝" },
  { name: "Kuru erik", amount: "5 adet", emoji: "🍑" },
  { name: "Üzüm", amount: "15 iri adet", emoji: "🍇" },
  { name: "Vişne", amount: "20 adet", emoji: "🍒" },
  { name: "Yenidünya (malta eriği)", amount: "5 adet", emoji: "🍑" },
  { name: "Yeşil erik", amount: "15 adet", emoji: "🟢" },
  { name: "Turna yemişi (kızılcık)", amount: "1 yemek kaşığı", emoji: "🔴" },
  { name: "Nektarin", amount: "1 adet küçük boy", emoji: "🍑" },
  { name: "Dut kurusu", amount: "2 yemek kaşığı", emoji: "🫐" },
  { name: "Aronya", amount: "1/3 su bardağı", emoji: "🫐" },
  { name: "Yaban mersini", amount: "½ su bardağı", emoji: "🫐" },
  { name: "Kumkat", amount: "3-4 adet", emoji: "🍊" },
];
